server:
  port: 8082
  servlet:
    contextPath: /phD_Garden
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phd_garden?user=root&serverTimezone=UTC
    password: root

